### PR TITLE
Initialize Guice after the environment has been set

### PR DESCRIPTION
**Pull request by chr1st1anh**
This is a simple way to achieve a lazier initialization of the guice injector. There are no tests that proof the singletons are working correctly. If you are willing to accept the pull request I might add some:).

### CODE REVIEW

**Comment by scho** [comment]
Does that mean, that we don't need to build our Guice bundle with ```Stage.DEVELOPMENT``` anymore?
That would be awesome!
I don't know much about Guice internals and the details about your implementation. So I can't really judge if your solution is the proper way to do it or not.

**Comment by chr1st1anh** [comment]
The change is very simple and its only about the time when guice is being initialized. This works for singletons that need the environment, so far nothing broke, but I haven't tested anything else. If I find a moment Ill look into tests from #70.

**Comment by jhaber** [comment]
This almost works but unfortunately breaks an important feature of dropwizard-guice that many people are depending on. You can't just move the call to `initialize` into the run phase like [this](https://github.com/HubSpot/dropwizard-guice/pull/76/files#diff-9230e43d0012c9b998723171b16e9b11R116) because it is too late to add bundles or configured bundles to the bootstrap by that point. I added a test in 4d079c98f026498ebc94e8514bd647b4c2c31f08 that shows the issue (the bundle will never be run).

Over time, however, we've found that auto config actually does more harm than good and we've moved away from it towards a more explicit model. We have another library, [HubSpot/dropwizard-guicier](https://github.com/HubSpot/dropwizard-guicier), that doesn't support auto config. It builds the injector during the run phase, runs in `Stage.PRODUCTION` by default, and has many other benefits. It does however still use dropwizard 0.7 and Jersey 1 at the moment, but I might try to upgrade it soon (boo HK2)

**Comment by chr1st1anh** [comment]
I see... we could not use autoconfig for another reason and maybe for this reason it did not give problems.

**Comment by jhaber** [comment]
Unfortunately I don't think we'll be able to fix this issue in dropwizard-guice, but I'd recommend checking out [HubSpot/dropwizard-guicier](https://github.com/HubSpot/dropwizard-guicier)

**Pull request closed without merging**
