### PR TITLE
do not attempt to create instances of abstract classes

### PR DESCRIPTION
**Pull request by smolloy**

### CODE REVIEW

**Comment by ParisMi** [comment]
Having this would be great.

**Comment by HiJon89** [comment]
Interfaces as well? I proposed this in #11 but my concern is that people could create bindings for abstract classes and interfaces, so I'm afraid this could break some people's existing code

**Comment by oillio** [comment]
There is another issue with the current design (not this pull request directly).  The AutoConfig only gets direct subtypes of a given class.
If you subtype Task with an abstract class (called AbstractTask), you might expect the AutoConfig to automatically add all subtypes of AbstractTask.  Currently, they will be ignored.

**Comment by ParisMi** [comment]
>If you subtype Task with an abstract class (called AbstractTask), you might expect the AutoConfig to automatically add all subtypes of AbstractTask. Currently, they will be ignored.

Just had this trouble myself -- it actually does. Make sure to provide the package that `AbstractTask` is located in to the autoconfig. Reflections doesn't even know that `AbstractImpl extends AbstractTask` and `Task` are related if it's not scanned.

>I'm afraid this could break some people's existing code
```
try {
environment.addHealthCheck(injector.getInstance(healthCheck));
} catch(ConfigurationException e) {
logger.warning("Not adding healthcheck " + healthCheck + " due to guice error", e);
continue;
}
}
```
or some variation?

**Comment by HiJon89** [comment]
@ParisMi I think that makes sense, except for the case where the call to `Injector#getInstance` fails because of a missing binding or missing `@Inject`, you probably wouldn't want dropwizard-guice to swallow those as your service could fail to start up later with a more cryptic error, or worse it could start up fully and start serving requests but not behave as expected. 

I can't think of a way to determine which Guice errors are safe to ignore. Every heuristic I can think of has plausible counterexamples. In light of that, I think the safest behavior is to autoconfig the packages we're asked to and propagate any Guice errors we get (ie, the current behavior). The only thing that comes to mind is maybe make it opt-in to ignore Guice errors.

**Comment by oillio** [comment]
@ParisMi - Yep, that was my problem.  Thanks.

**Comment by jhaber** [comment]
Fixed in 2ea01f2f1a7b5fdd55fcde9a1545a62b31a6b932

**Pull request closed without merging**
