### PR TITLE
[issue-98] Register GuiceServletContextListener

### PR DESCRIPTION
**Pull request by ikatkov**
Please see https://github.com/HubSpot/dropwizard-guice/issues/98

### CODE REVIEW

**Comment by ikatkov** [comment]
Can't add reviewers. 
@jhaber @chrisburke1 see this PR

**Comment by ikatkov** [comment]
ping?

**Comment by ikatkov** [comment]
pong?

**Comment by ikatkov** [comment]
anyone?

**Comment by jhaber** [comment]
Sorry for the delay, this lgtm (looks like it was already added to dropwizard-guicier [here](https://github.com/HubSpot/dropwizard-guicier/blob/fb7839fe07ebee89674d6120c45941517f7fc196/src/main/java/com/hubspot/dropwizard/guicier/GuiceBundle.java#L115-L120))

**Pull request merged**
